# Generated by Django 4.1.7 on 2023-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_watchlist_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
